export const metadata = {

    title: "Next App",
    description: "Generated by create next app",
    img:"https://images.pexels.com/photos/3183198/pexels-photo-3183198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    url: "https://fullstacknextjs-n81myrmpe-brainscollides-projects.vercel.app/",
    type:"Website"

  };