export const metadata = {
    title: "Next App",
    description: "Generated by create next app",
    img:"https://www.pexels.com/photo/top-view-photo-of-person-holding-earphones-3183198/",
    url: "https://fullstacknextjs-n81myrmpe-brainscollides-projects.vercel.app/",
    type:"Website"

  };